#! /bin/bash
export LANG=zh_TW.UTF-8
export LC_ALL=zh_TW.UTF-8
if [[ -f  ~/.wine/drive_c/users/lecheel/Application\ Data/baidu/BaiduYunGuanjia/BaiduYunGuanjia.exe ]]; then
   wine ~/.wine/drive_c/users/lecheel/Application\ Data/baidu/BaiduYunGuanjia/BaiduYunGuanjia.exe >/dev/null 2>&1 &
else
   echo -e "o  \033[91mBaidu\033[95mYun\033[0m is not available!!!"
fi
