#! /bin/bash
if [[ -f ~/.wine/drive_c/ap/ConvertZ/ConvertZ.exe ]]; then
    echo "-- Active ConvertZ...."
    wine ~/.wine/drive_c/ap/ConvertZ/ConvertZ.exe > /dev/null 2>&1 &
else
    echo -e "-- No \033[93mConvertZ\033[0m is installed" 
fi		
