#! /bin/bash
if [ $# -eq 0 ]; then
    echo "AutoJad from APK v0.1 ..."
else
	if [ -e $@ ]; then
                mkdir ooo
                cd ooo
        	unzip ../$1 classes.dex
                /opt/app/sign/dex2jar classes.dex
                unzip classes_dex2jar.jar
                rm -f classes.dex
                rm -f classes_dex2jar.jar
                cd com
                find ./ -name *.class -exec jad {} \;
                jad -o -r -sjava -d src com/**/*.class


                cd ..
                cd at
                find ./ -name *.class -exec jad {} \;
                jad -o -r -sjava -d src at/**/*.class
                
        fi
fi