#! /bin/bash
if [[ "$1" == "" ]]; then
    echo " Usage: ...."
    echo "  0   -- Accepted log"
    echo "  1   -- Refused log  -11 Failed"
    echo "  2   -- Denyhost   -20"
    echo "  3   -- vchun LOGO -30,31,32"
    echo "  4   -- TBD"
    echo "  5   -- Daily HIT history"
    exit
fi
if [[ "$1" == "0" ]]; then
    grep --color=auto Accept /var/log/auth.log
    echo "show Accpeded"
    exit
fi
DAY=`date +"%d"`

if [[ "$1" == "1" ]]; then
    grep --color=auto ref /var/log/auth.log|grep --color=auto " "$DAY" "
    grep --color=auto ref /var/log/auth.log|grep --color=auto " "$DAY" "|wc
    echo -e "show Reject Today"
    exit
fi

if [[ "$1" == "11" ]]; then
    grep --color=auto -E -o ".{0,60}Failed.{0,30}" /var/log/auth.log|grep --color=auto " "$DAY" "
    grep --color=auto Failed /var/log/auth.log|grep --color=auto " "$DAY" "|wc
    echo -e "show Failed Today"
    exit
fi

if [[ "$1" == "12" ]]; then
    grep --color=auto -E -o ".{0,60}Failed.{0,30}" /var/log/auth.log
    grep --color=auto Failed /var/log/auth.log|wc
    echo -e "show Failed auth.log"
    exit
fi



if [[ "$1" == "2" ]]; then
DAY=`date +"%Y\-%m\-%d"`    
    grep --color=auto denied /var/log/denyhosts|grep --color=auto $DAY
    grep --color=auto ref /var/log/auth.log|grep --color=auto $DAY|wc
    echo -e "show Denyhosts Today"
    exit
fi


if [[ "$1" == "20" ]]; then
DAY=`date +"%Y\-%m\-%d"`    
    grep --color=auto denied /var/log/denyhosts
    echo -e "show Denyhosts "
    exit
fi

if [[ "$1" == "3" ]]; then
    grep --color=auto vchuncount /var/log/apache2/access.log
    echo -e "show VCHUN HIT counts"
    exit
fi

if [[ "$1" == "30" ]]; then
    # grep --color=auto vchun_banner03 /var/log/apache2/access.log | cut -d'H' -f1|grep --color=auto 0800
    grep --color=auto -E -o ".{0,60}vchun_banner03" /var/log/apache2/access.log
    echo -e "show VCHUN LOGOs"
    exit
fi

if [[ "$1" == "31" ]]; then
    grep --color=auto vchuncount /var/log/apache2/access.log
    echo -e "show VCHUN HIT COUNT"
    exit
fi

if [[ "$1" == "32" ]]; then
    grep --color=auto vchuncount /var/log/apache2/access.log.1
    echo -e "show VCHUN LOGOs"
    exit
fi

if [[ "$1" == "33" ]]; then
    grep --color=auto vchun_banner03 /var/log/apache2/access.log.1
    echo -e "show VCHUN LOGOs"
    exit
fi

if [[ "$1" == "4" ]]; then
    cd /var/www/lenum
    ./hits.sh
    echo -e "show VCHUN LOGOs"
    exit
fi

if [[ "$1" == "5" ]]; then
    cd /var/www/lenum
    tail -5 /var/www/lenum/daily.log
    exit
fi

if [[ "$1" == "50" ]]; then
    cd /var/www/lenum
    tac /var/www/lenum/daily.log
    exit
fi


