#! /bin/bash
if [[ -f ~/.wine/drive_c/ap/ps7/Photoshop.exe ]]; then
    echo "Active ps7...."
    wine ~/.wine/drive_c/ap/ps7/Photoshop.exe > /dev/null 2>&1 &
else 
    wine ~/.wine/drive_c/Program\ Files\ \(x86\)/Adobe/Photoshop\ 7.0/Photoshop.exe > /dev/null 2>&1 &
fi		
