#! /bin/bash
if [ -f ~/.wine/drive_c/ap/uedit/uedit32.exe ]; then
    echo -e "--  Active uedit \033[92m32\033[0m "
   wine ~/.wine/drive_c/ap/uedit/uedit32.exe $@ > /dev/null 2>&1 &
else
    echo -e "--  uedit \033[92m32\033[0m not installed!"
fi
